"""adiciona model de embarque e excursao

Revision ID: 068aa4f41f56
Revises: e064408f04d4
Create Date: 2026-07-02 01:15:20.961609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068aa4f41f56'
down_revision = 'e064408f04d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embarque',
    sa.Column('local_embarque', sa.String(length=200), nullable=True),
    sa.Column('horario_embarque', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('excursao',
    sa.Column('hotel', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('destino', sa.String(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('data_retorno', sa.Date(), nullable=True),
    sa.Column('status_viagem', sa.Enum('CONCLUIDA', 'EM_ANDAMENTO', 'CANCELADA', name='statusviagem'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embarque_excursao',
    sa.Column('excursao_id', sa.UUID(), nullable=True),
    sa.Column('embarque_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['embarque_id'], ['embarque.id'], ),
    sa.ForeignKeyConstraint(['excursao_id'], ['excursao.id'], )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('embarque_excursao')
    op.drop_table('excursao')
    op.drop_table('embarque')
    # ### end Alembic commands ###
