"""adiciona todas as tabela

Revision ID: 0b7f0ebb7003
Revises: 
Create Date: 2026-07-20 20:59:53.978370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7f0ebb7003'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onibus',
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('capacidade_assento', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('titular_id', sa.UUID(), nullable=True),
    sa.Column('endereco_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['titular_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('excursao',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('hotel', sa.String(), nullable=True),
    sa.Column('valor_por_pessoa', sa.Float(), nullable=False),
    sa.Column('data_saida', sa.DateTime(), nullable=False),
    sa.Column('data_retorno', sa.DateTime(), nullable=False),
    sa.Column('destino_id', sa.UUID(), nullable=False),
    sa.Column('onibus_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destino_id'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['onibus_id'], ['onibus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('vendas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('excursao_id', sa.UUID(), nullable=False),
    sa.Column('cliente_titular_id', sa.UUID(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('status_pagamento', sa.String(length=20), nullable=True),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_titular_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['excursao_id'], ['excursao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendas_id'), ['id'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venda_id', sa.UUID(), nullable=False),
    sa.Column('passageiro_id', sa.UUID(), nullable=False),
    sa.Column('numero_assento', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['passageiro_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_id'))

    op.drop_table('reservas')
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_id'))

    op.drop_table('vendas')
    op.drop_table('excursao')
    op.drop_table('clientes')
    op.drop_table('onibus')
    op.drop_table('enderecos')
    # ### end Alembic commands ###
