"""create users and endereco

Revision ID: 410ca8f3509b
Revises: 
Create Date: 2026-07-17 20:29:00.588430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410ca8f3509b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('endereco_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('enderecos')
    # ### end Alembic commands ###
