"""first tables

Revision ID: 9f6089e2887a
Revises: 
Create Date: 2026-06-25 18:23:18.373913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6089e2887a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_default',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_default')
    # ### end Alembic commands ###
